export const BarChartDatas = [
  {
    country: "AD",
    "hot dog": 2,
    burger: 1,
    sandwich: 2,
    kebab: 1,
    fries: 1,
    donut: 1,
  },
  {
    country: "AE",
    "hot dog": 1,
    burger: 2,
    sandwich: 2,
    kebab: 1,
    fries: 1,
    donut: 1,
  },
  {
    country: "AF",
    "hot dog": 2,
    burger: 2,
    sandwich: 1,
    kebab: 1,
    fries: 1,
    donut: 1,
  },
  {
    country: "AG",
    "hot dog": 2,
    burger: 1,
    sandwich: 2,
    kebab: 1,
    fries: 1,
    donut: 1,
  },
  {
    country: "AI",
    "hot dog": 1,
    burger: 2,
    sandwich: 2,
    kebab: 1,
    fries: 1,
    donut: 1,
  },
  {
    country: "AL",
    "hot dog": 2,
    burger: 2,
    sandwich: 1,
    kebab: 1,
    fries: 1,
    donut: 1,
  },
  {
    country: "AM",
    "hot dog": 1,
    burger: 2,
    sandwich: 2,
    kebab: 1,
    fries: 1,
    donut: 1,
  },
];
